name: data

on:
  push:
    branches:
      - main
    paths:
      - "data/**"
  pull_request:
    paths:
      - "data/**"
  schedule:
    # "At 12:00 in every month from July through October."
    # https://crontab.guru/#0_*/4_*_7-10_*
    - cron: "0 */4 * 7-10 *"
  workflow_dispatch:

jobs:
  test:
    name: Test Data
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: data
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"
          cache-dependency-path: data/requirements.txt
      - run: python3 -m pip install -r requirements.txt
      - run: python3 -m pip install pytest pytest-cov
      - run: python3 -m pytest tests/ -v --cov=. --cov-report=xml
      - uses: codecov/codecov-action@v3
        with:
          files: data/coverage.xml
          flags: data
          fail_ci_if_error: false

  scrape:
    name: Scrape Data
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v3
      - uses: browser-actions/setup-chrome@latest
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"
      - run: python3 -m pip install -r ./data/requirements.txt
      - run: python3 ./data/main.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CF_DISTRIBUTION: ${{ secrets.CF_DISTRIBUTION }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
